version: 0.0.1.{build}

pull_requests:
  do_not_increment_build_number: true

install:
- ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-beta-i686-pc-windows-gnu.exe'
- rust-beta-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
- SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
- rustc -V
- cargo -V

build_script:
- cargo build --release

test_script:
- cargo test --verbose

artifacts:
- path: target/release/share_a_secret.exe
