language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev # REQUIRED: pip
      - libelf-dev # REQUIRED: coveralls / travis-cargo
      - libdw-dev # REQUIRED: coveralls / travis-cargo

rust:
  - stable
  - beta
  - nightly

matrix:
   allow_failures:
     - rust: nightly

before_script:
  - pip install travis-cargo --user

after_success:
  - travis-cargo coveralls --no-sudo
